// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwGxRBWzqMVRV_BpMneS3CNc-dtDuOMgY',
    appId: '1:438344204669:web:6b37b170f8f7e0523f4c14',
    messagingSenderId: '438344204669',
    projectId: 'embsystem-8291f',
    authDomain: 'embsystem-8291f.firebaseapp.com',
    storageBucket: 'embsystem-8291f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo9zCLLVLLu3nyV4JPrRotJ75QHv1oeqY',
    appId: '1:438344204669:android:c6ddb277471958033f4c14',
    messagingSenderId: '438344204669',
    projectId: 'embsystem-8291f',
    storageBucket: 'embsystem-8291f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgw-5rqvL1w2HJGmj75NZPB2xJaq5_BSU',
    appId: '1:438344204669:ios:7267e7cfc03cbb733f4c14',
    messagingSenderId: '438344204669',
    projectId: 'embsystem-8291f',
    storageBucket: 'embsystem-8291f.appspot.com',
    iosBundleId: 'com.example.embededSystemProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgw-5rqvL1w2HJGmj75NZPB2xJaq5_BSU',
    appId: '1:438344204669:ios:7267e7cfc03cbb733f4c14',
    messagingSenderId: '438344204669',
    projectId: 'embsystem-8291f',
    storageBucket: 'embsystem-8291f.appspot.com',
    iosBundleId: 'com.example.embededSystemProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwGxRBWzqMVRV_BpMneS3CNc-dtDuOMgY',
    appId: '1:438344204669:web:e985cb760934ca203f4c14',
    messagingSenderId: '438344204669',
    projectId: 'embsystem-8291f',
    authDomain: 'embsystem-8291f.firebaseapp.com',
    storageBucket: 'embsystem-8291f.appspot.com',
  );
}
